### PR TITLE
Update swagger_parser.py

### PR DESCRIPTION
**Pull request by crudo10**
This patch addresses issues #31, 32, 33

### CODE REVIEW

**Comment by cyprieng** [comment]
Hi thanks for reporting issues and fixing them :+1:  
I think you made a mistake in your PR, you mean to merge it in https://github.com/Trax-air/swagger-parser master, right ?

**Comment by crudo10** [comment]
Hi,
I am new to github and I am not a Python expert so please make sure that my fixes are not breaking anything else.
Best regards.

Sent from my Samsung device

-------- Original message --------

**Comment by cyprieng** [comment]
Yes of course I will check. But first the PR target need to be trax-air/swagger-parser:master not your fork master, so you need to create a new PR. That will allow the test to run.

**Comment by crudo10** [comment]
Wrong PR

**Pull request closed without merging**
